#!/bin/sh
#CACHE=$HOME/.dmenu_cache
CACHE="/tmp/.${USER}-dmenu_cache"
IFS=:

source ~/.bashrc

uptodate() {
	test ! -f $CACHE && return 1
	for dir in $PATH
	do
		test $dir -nt $CACHE && return 1
	done
	return 0
}

if ! uptodate
then
    (
        ~/scripts/assign_tags_to_apps.rb | awk '{print $1}'
        for dir in $PATH
        do
            for file in "$dir"/*
            do
                test -x "$file" && echo "${file##*/}"
                #test -x "$file" && (ldd "$file" | grep libX11) > /dev/null 2>&1 && echo "${file##*/}"
            done
        done
    ) | sort | uniq > $CACHE.$$
	mv $CACHE.$$ $CACHE
fi

cat $CACHE
