#!/bin/sh

DIR=$HOME'/screens'
CF="$DIR/.counter"

NUM=$(($(cat "${CF}") + 1)) && echo $NUM > "${CF}"
FILENAME="$DIR/screenshot_$(printf '%08d\n' "${NUM}").png"

if [[ $1 == area ]]; then
    (import $FILENAME && feh $FILENAME) || xmessage 'import failed'
else
    scrot ${FILENAME} && feh ${FILENAME}
fi
