#status-msg="Time: ${time-pos} (${=audio-pts} / ${playback-time})"
status-msg="Time: ${time-pos} / ${duration} ${percent-pos}%"
#status-msg="${=audio-pts}"
screenshot-format=png
#alsa-ignore-chmap
#volume=50
volume=90
volume-max=300
#audio-channels=2
#hwdec=vaapi
save-position-on-quit
#af=chromium
af=scaletempo2
#af=scaletempo2=max-speed=10 # TODO
#af=rubberband
osd-font-size=40 # for playlist/F8
# sub-font-size=44
no-sub-visibility # press v to show
fullscreen

# nvidia
vo=gpu
gpu-api=vulkan
hwdec=nvdec
hwdec-codecs=all

# for https://github.com/TheAMM/mpv_thumbnail_script
osc=no

# FPS
#video-sync=display-desync
#osd-msg1="FPS: ${estimated-display-fps}"

# yt-dlp: use /etc/yt-dlp.conf instead of ytdl-format/ytdl-raw-options
force-seekable=yes
#cache-pause=no
# doesn't work with /etc/yt-dlp.conf
#ytdl-raw-options='sub-lang="en,eng,enUS,en-US,en-en,ru,rus,ru-ru",write-sub='
ytdl-raw-options='sub-lang=none,write-sub='
#ytdl-raw-options='sub-lang=none,write-sub= --paths=temp:/var/tmp/000 --keep-fragments'
#ytdl-raw-options='paths=temp:/var/tmp/000/ --keep-fragments'


#script-opts-add=osc-title=${media-title}${?chapter-metadata/title: [${chapter-metadata/title}]}
