#af=chromium
af=scaletempo2
#af=scaletempo2=max-speed=10 # TODO
#af=rubberband

fullscreen

speed=2.2
af-add='lavfi=[dynaudnorm=f=75:g=25:p=0.55]' # normalize sound volume

# boost speech volume
#af=@normalize:speechnorm=e=10:r=0.0005:l=1
# loudnorm works well too, but uses more CPU
#af=@normalize:loudnorm=I=-10

#volume=50
volume=90
volume-max=300

#status-msg="Time: ${time-pos} (${=audio-pts} / ${playback-time})"
status-msg="Time: ${time-pos} / ${duration} ${percent-pos}%"
#status-msg="${=audio-pts}"
screenshot-format=png
#alsa-ignore-chmap
#audio-channels=2
#hwdec=vaapi
save-position-on-quit

#osd-font='Iosevka Term SS08'
osd-font='Roboto Bold'
osd-font-size=60 # for playlist/chapters
osd-border-size=5
# sub-font-size=44
no-sub-visibility # press v to show subtitles
#osd-duration=4000

# nvidia
vo=gpu
gpu-api=vulkan
hwdec=nvdec
hwdec-codecs=all

# for https://github.com/TheAMM/mpv_thumbnail_script
osc=no

# FPS
#video-sync=display-desync
#osd-msg1="FPS: ${estimated-display-fps}"

# yt-dlp + /etc/yt-dlp.conf?
force-seekable=yes
#cache-pause=no
#ytdl-format="best[height<=1080][ext=mp4][protocol!*=dash]/bestvideo+bestaudio"
#ytdl-format="best[height<=1080][ext=mp4][protocol!*=dash]"
#ytdl-format='bestvideo+bestaudio'
#ytdl-format="best[height<=1081][ext=mp4][protocol!*=dash]"
#ytdl-format="270+251/best[height<=1080]"
#ytdl-format="399+251/best[height<=1080]"
ytdl-format="best[height<=1080]"
#ytdl-format='bestvideo[height<=?1080]+bestaudio/best[height<=?1080]'
#ytdl-raw-options='sub-lang="en,eng,enUS,en-US,en-en,ru,rus,ru-ru",write-sub='
#ytdl-raw-options='sub-lang=none,write-sub='




ytdl-raw-options='sub-lang=none,write-sub='


#ytdl-raw-options='sub-lang=none,write-sub= --paths=temp:/var/tmp/000 --keep-fragments'
#ytdl-raw-options='paths=temp:/var/tmp/000/ --keep-fragments'

#script-opts-add=osc-title=${media-title}${?chapter-metadata/title: [${chapter-metadata/title}]}
