#!/bin/bash

su sbar -c 'DISPLAY=:0 XAUTHORITY=~sbar/.Xauthority /home/sbar/.bin/alock' &
#su sbar -c 'echo disconnect >> /home/sbar/.mcabber/mcabber.fifo'
#su sbar -c 'DISPLAY=:0 /usr/bin/gajim-remote change_status offline'
su sbar -c 'DISPLAY=:0 /usr/bin/psi-plus --remote --status=offline'
service acpid stop
mpc stop
umount /nfs/router &
/etc/init.d/alsasound restore
chvt 5

swapon /dev/disk/by-label/swap
echo -n disk > /sys/power/state
swapoff -a

hdparm -B 254 /dev/sda >> /dev/null
echo "keycode 14 = BackSpace" | loadkeys &
#service mpdscribble restart
(sleep 3 && service net.wlan0 restart) &
(service acpid restart; service acpid restart; service cpufreqd start) &
service hddtemp restart &
#/etc/init.d/consolefont restart
#/etc/init.d/hwclock restart
#(sleep 10 && /etc/cron.daily/ntpdate) &
#amixer sset Master unmute &
#v4l2ctrl -l /etc/v4l2ctrl/7fpsLight.vbi 2&>> /dev/null &
v4l2ctrl -l /etc/v4l2ucp/bright.vbi 2&>> /dev/null &
(sleep 10 && /etc/init.d/mpdscribble restart) &

/usr/local/sbin/camshot &
