#!/bin/bash

#watch -n1 'echo "gcc instances $(ps uax | grep /gcc | grep -v grep | wc -l)" ; echo "emerge instances $(ps uax | grep /emerge | grep -v grep | wc -l)" ; echo ; echo ; sensors ; iwconfig ; tail -n10 /var/log/messages ; grep MHz /proc/cpuinfo ; cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor ; df -h /'

S='echo "gcc instances $(ps uax | grep /gcc | grep -v grep | wc -l)";'
S+='echo "emerge instances $(ps uax | grep /emerge | grep -v grep | wc -l)";'
S+='echo;'
S+='sensors;'
S+='iwconfig;'
S+='tail -n10 /var/log/messages;'
S+='echo;'
S+='grep MHz /proc/cpuinfo;'
S+='cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor;'
S+='df -h /;'

watch -n1 "${S}"
