#!/bin/sh

DIR=$HOME'/screens'
COUNTER=.counter
#FILENAME=$DIR'/screenshot_'$((`ls -1 $DIR|tail -n1|tr -d '[a-z\._]'`+1))'.png'
NUM=$(($(cat "$DIR/$COUNTER") + 1)) && echo $NUM > "$DIR/$COUNTER"
FILENAME="$DIR/screenshot_$NUM.png"
scrot ${FILENAME} && feh ${FILENAME}
