#!/bin/bash

killall -9 xkill 2&> /dev/null
#/usr/local/bin/alock -bg image:center,file=/home/sbar/pix/locked.png -cursor theme:name=mini -auth passwd
#/usr/bin/alock -bg image:center,file=/home/sbar/pix/locked.png -cursor theme:name=mini -auth pam
/home/sbar/coding/github/alock/src/alock -bg image:center,file=/home/sbar/pix/locked.png -cursor theme:name=mini -auth pam
