#!/bin/bash
DATE=$(date +%s)
sudo /usr/local/bin/snapscreenshot > /var/tmp/console-${DATE}.tga
convert +matte /var/tmp/console-${DATE}.tga ~sbar/screens/console-${DATE}.png
rm -f /var/tmp/console-${DATE}.tga >> /dev/null
