#!/bin/bash

# remove at least 30 days old non-dot files/directories
find /coredumps/ /home/*/Downloads/ /var/tmp/portage/ /var/tmp/al_mpv_thumbnails/ -mindepth 1 -not -path '*/.*' -mtime +30 -exec rm -fr {} \;

find /home/*/.debug/ /root/.debug/ /home/*/.cache/thumbnails/*/ -type f -mindepth 1 -mtime +30 -exec rm -f {} \;
find /root/.vimundo/ -type f -mindepth 1 -mtime +90 -exec rm -f {} \;

find ~al/video/screen/ -type f -size 0 -delete

find / -type d -name __MACOSX -exec rm -rf {} +
