#!/bin/bash

# remove at least 30 days old non-dot files/directories
find /coredumps/ /home/*/Downloads/ /var/tmp/portage/ /var/tmp/al_mpv_thumbnails/ -mindepth 1 -not -path '*/.*' -mtime +30 -exec rm -fr {} +

find /home/*/.debug/ /root/.debug/ /home/*/.cache/thumbnails/*/ /home/*/.cache/go-build/ /home/*/.cache/kdenlive/proxy/ -type f -mtime +30 -exec rm -f {} +
find /home/*/.android/avd/*/snapshots -type d -mtime +30 -exec rm -fr {} +
find /root/.vimundo/ -type f -mtime +90 -exec rm -f {} +

find ~al/video/screen/ -type f -size 0 -delete

find / /mnt/lenslowssd -xdev -type d -name __MACOSX -exec rm -rf {} +

flatpak uninstall --unused --noninteractive
su al -c 'flatpak uninstall --unused --noninteractive'

docker image prune --all --force
docker volume prune --force
docker network prune --force
docker builder prune --force

su al -c '~/scripts/compress_pictures.sh /home/al/.private/backups/phones'

#su al -c 'cd /home/al/pictures && ~/.cargo/bin/deduplicator'
