#!/bin/sh

bluetoothctl power off

# https://marc.info/?l=linux-usb&m=121459435621262
usbreset $(lsusb -d 0cf3: | perl -nE "/\D+(\d+)\D+(\d+).+/; print qq(/dev/bus/usb/\$1/\$2)")

bluetoothctl power on
