#!/bin/bash

CDIR="/tmp/chromium-cache-anon-proxy-${USER}"

mkdir -p "${CDIR}"

# --ppapi-flash-path=/usr/lib64/nsbrowser/plugins/PepperFlash/libpepflashplayer.so --ppapi-flash-version=15.0.0.152

# --enable-native-gpu-memory-buffers
#

PROXY=http://127.0.0.1:58889
#PROXY=socks5://127.0.0.1:1024

TZ=UTC /usr/bin/chromium-bin --incognito \
        --proxy-server=${PROXY} \
         --disk-cache-dir=${CDIR} \
            --disable-sync-preferences --ignore-gpu-blacklist --enable-gpu-rasterization --disable-crashpad --force-device-scale-factor=2.5 --process-per-site --enable-features=WebUIDarkMode --enable-features=VaapiIgnoreDriverChecks --disable-features=UseChromeOSDirectVideoDecoder --disable-gpu-vsync=beginframe \
         --user-data-dir=/home/al/.private/chromium-anon-proxy $@
rm -rf "${CDIR}"
