#!/bin/sh

sudo /etc/init.d/autofs restart
sudo umount -fl /nfs/mind
ssh mind 'sudo /etc/init.d/nfs restart ; sudo /etc/init.d/autofs restart ; sudo umount -fl /media/rhome ; ls /media/rhome'
ls /nfs/mind
