#!/bin/bash

IFACE=wlp7s0

(sudo /bin/ifconfig ${IFACE} | grep UP >> /dev/null) || \
    sudo ifconfig ${IFACE} up || exit 1

sudo /sbin/iwlist ${IFACE} scan \
    | egrep -i '(encr|essid|quali|freq)' \
    | sed 's!^ *!!g;s!^Freq!\nFreq!g'
