#!/bin/bash

function find_socket_file() {
    project_dir=$(pwd)
    while [ ! -z "${project_dir}" ]; do
        socket_file="/tmp/nvim-$(echo ${project_dir} | sed 's!/!%!g')"
        if [ -S "${socket_file}" ]; then
            break
        fi
        project_dir="${project_dir%/*}"
    done
    echo "${socket_file}"
}

files=( "$@" )
cmd=''
for ((i=${#files[@]}-1; i>=0; i--)); do
    item="${files[$i]}"
    filename=$(echo "${item}" | cut -d':' -f1)
    filename=$(printf '%q' "${filename}")
    line=$(echo "${item}" | cut -d':' -f2)
    column=$(echo "${item}" | cut -d':' -f3)
    cmd+="<esc>:tab drop ${filename}<cr>${line}G${column}|"
done

NVIM_LISTEN_ADDRESS="$(find_socket_file)" nvr -s --nostart --remote-send "${cmd}"
