#!/bin/bash

workspace_root="$1"
workspace_root_escaped=$(echo "$1" | sed 's!/!%!g')
nvim_listen_address="/tmp/nvim-cargo-limit-${USER}-${workspace_root_escaped}"

shift
files=( "$@" )
cmd=''
for ((i=${#files[@]}-1; i>=0; i--)); do
    item="${files[$i]}"
    filename=$(echo "${item}" | cut -d':' -f1)
    filename=$(printf "${workspace_root}/%q" "${filename}")
    line=$(echo "${item}" | cut -d':' -f2)
    column=$(echo "${item}" | cut -d':' -f3)
    cmd+="<esc>:tab drop ${filename}<cr>${line}G${column}|"
done

nvr -s --nostart --servername "${nvim_listen_address}" --remote-send "${cmd}"
