#!/bin/sh

pwd_escaped=$(pwd | sed 's!/!%!g')
item="${1}"
filename=$(echo "${item}" | cut -d':' -f1)
line=$(echo "${item}" | cut -d':' -f2)
column=$(echo "${item}" | cut -d':' -f3)
NVIM_LISTEN_ADDRESS="/tmp/nvim-${pwd_escaped}" nvr -s --nostart --remote-send "<esc>:tab drop ${filename}<cr>${line}G${column}|"
