#!/bin/sh

# TODO: -acodec pcm_s16le -vcodec libx264 -vpre lossless_ultrafast -threads 0 -y out.mkv
# TODO: time limit

if [ "$1" = '-h' ]; then
    echo "syntax: $0 [all-sound|mic-only|system-only|no-sound] [low|high] [mouse|no-mouse]"
    echo "defaults are: $0 all-sound high"
    exit 1
fi

DEVICE="$1"
QUALITY="$2"
MOUSE="$3"
VIDEO_SIZE=$(xdpyinfo | awk '/dimensions:/ { print $2; exit }')
#VIDEO_SIZE="1696x73"
OUTPUT="${HOME}/video/screen/$(date --rfc-3339=seconds).mp4"

kill_ffmpeg_on_error () {
    grep -m1 'ALSA read error: No such device' >>/dev/null && {
        ffmpeg_pid=$(ps uax | grep -E 'ffmpeg.*x11grab' | grep -v grep | awk '{print $2}')
        if [[ "${ffmpeg_pid}" != '' ]]; then
            kill "${ffmpeg_pid}"
            exit 1
        fi
    }
    exit 0
}

case "${DEVICE}" in
    mic-only)
        #SOUND_INPUT=shared_input_zoom_recorder_redirect_left_channel_to_right
        SOUND_INPUT=zoom_recorder
        ;;
    system-only)
        SOUND_INPUT=shared_input_loopback
        ;;
    no-sound)
        SOUND_INPUT=
        ;;
    *)
        SOUND_INPUT=input_LOOPBACK_and_zoom_recorder
        ;;
esac

if [ "${QUALITY}" = 'low' ]; then
    CHANNELS=1
    SOUND_RATE=22050
    FRAMERATE=15
    #CRF=23
    #CRF=18
    CRF=37
else
    CHANNELS=2
    SOUND_RATE=48000
    FRAMERATE=60
    CRF=18
fi

if [ "${MOUSE}" = 'no-mouse' ]; then
    DRAW_MOUSE=0
else
    DRAW_MOUSE=1
fi

# -i :0.0+54,6
if [ ! "${SOUND_INPUT}" ]; then
    ffmpeg \
        -thread_queue_size 512 \
        -video_size "${VIDEO_SIZE}" \
        -framerate "${FRAMERATE}" \
        -f x11grab \
        -draw_mouse "${DRAW_MOUSE}" \
        -i :0.0+0,0 \
        -vcodec libx264 -preset ultrafast -crf "${CRF}" \
        "${OUTPUT}" 2>>/dev/stdout | tee /dev/stderr | kill_ffmpeg_on_error
else
    ffmpeg \
        -thread_queue_size 512 \
        -video_size "${VIDEO_SIZE}" \
        -framerate "${FRAMERATE}" \
        -f x11grab \
        -draw_mouse "${DRAW_MOUSE}" \
        -i :0.0+0,0 \
        -thread_queue_size 512 \
        -f alsa \
        -ac "${CHANNELS}" \
        -i "${SOUND_INPUT}"  \
        -ar "${SOUND_RATE}" \
        -vcodec libx264 -preset ultrafast -crf "${CRF}" \
        -acodec alac \
        -f ipod \
        "${OUTPUT}" 2>>/dev/stdout | tee /dev/stderr | kill_ffmpeg_on_error
fi

EXIT_CODE="$?"
echo "${OUTPUT}"
exit "${EXIT_CODE}"
