#!/bin/sh

set -e

#export RUSTFLAGS="-C target-cpu=native"
export RUSTFLAGS="-C target-cpu=native -C force-frame-pointers=y"

#RUST_NIGHTLY_VERSION="nightly-2020-07-18"
#rustup +${RUST_NIGHTLY_VERSION} component add miri

#RUST_NIGHTLY_VERSION="nightly-2021-05-07"
#RUST_NIGHTLY_VERSION="nightly-2021-06-09"
#RUST_NIGHTLY_VERSION="nightly-2021-10-21"
#RUST_NIGHTLY_VERSION="nightly-2023-02-09"
#RUST_NIGHTLY_VERSION="nightly-2025-04-14" # https://rust-lang.github.io/rustup-components-history/
#RUST_NIGHTLY_VERSION="nightly-2025-08-18"
RUST_NIGHTLY_VERSION="nightly-2026-03-07"
#RUST_STABLE_VERSION="1.74.0-x86_64-unknown-linux-gnu"
#RUST_STABLE_VERSION="1.81.0-x86_64-unknown-linux-gnu"
#RUST_STABLE_VERSION="1.86.0-x86_64-unknown-linux-gnu"
#RUST_STABLE_VERSION="1.89.0-x86_64-unknown-linux-gnu"
#RUST_STABLE_VERSION="1.92.0-x86_64-unknown-linux-gnu"
#RUST_STABLE_VERSION="1.93.0-x86_64-unknown-linux-gnu"
#RUST_STABLE_VERSION="1.94.0-x86_64-unknown-linux-gnu"
RUST_STABLE_VERSION="1.95.0-x86_64-unknown-linux-gnu"
#RUST_ANALYZER_VERSION="2023-03-06"
#RUST_ANALYZER_VERSION="2023-09-04"
#RUST_ANALYZER_VERSION="2023-11-27"
#RUST_ANALYZER_VERSION="2024-10-07"
#RUST_ANALYZER_VERSION="2025-04-07"
#RUST_ANALYZER_VERSION="2025-08-11"
#RUST_ANALYZER_VERSION="2025-08-25"
#RUST_ANALYZER_VERSION="2025-01-26"
RUST_ANALYZER_VERSION="2026-03-02"

rustup install "${RUST_NIGHTLY_VERSION}"
rustup component add --toolchain "${RUST_NIGHTLY_VERSION}" rustfmt
ln -sf ~/.rustup/toolchains/${RUST_NIGHTLY_VERSION}-x86_64-unknown-linux-gnu/bin/rustfmt ~/.bin/rustfmt

rustup install "${RUST_STABLE_VERSION}"
rustup default "${RUST_STABLE_VERSION}"
#rustup component add clippy rust-src rust-analyzer
rustup component add clippy rust-src
rm -fv ~/docs/rust ; ln -sf $(rustc --print sysroot)/share/doc/rust/html ~/docs/rust

#cargo +${RUST_NIGHTLY_VERSION} install --locked --features simd-accel ripgrep
#cargo +nightly install --locked --features simd-accel ripgrep
#cargo install --locked skim fd-find xcp deduplicator hyperfine intentrace mergiraf difftastic
#cargo install --locked --force --git https://github.com/lbeder/qrcode-cli --tag 0.4.0

cd ~/git-extra/rust-analyzer
git checkout master
git clean -f -x -d .
git pull -v
git fetch origin "${RUST_ANALYZER_VERSION}"
git checkout "${RUST_ANALYZER_VERSION}"
RUSTFLAGS="-C target-cpu=native" ~/.cargo/bin/cargo xtask install --server
RUSTFLAGS="-C target-cpu=native" ~/.cargo/bin/cargo xtask install
cd

##rustup self update
##rustup update
##rustup default stable
##
##npm update
##npm audit fix --force
##
##go get -u -v all
##go get -d github.com/google/fscrypt/...
##go get github.com/google/fscrypt/cmd/fscrypt
##
##pip3 list --outdated --format=freeze | grep -v '^\-e' | grep -v '^pip$' | cut -d = -f 1 | xargs -n1 pip3 install --upgrade --user
##pip2 freeze --local | grep -v '^\-e' | cut -d = -f 1 | grep -v '^pip$' | xargs -n1 pip2 install --upgrade --user
##
##/usr/bin/nvim +PlugInstall +UpdateRemotePlugins +qa
##
##gem install rubocop nokogiri acoc jekyll bundler open3 rubydns parallel inifile rubydns
##sudo gem install rubydns
##
##sudo layman -S
##sudo emerge --sync
##eix-update
###emerge -pve @system
###emerge -pvuDN @world
##em-auto-exclude.rb -uDNa @world

#go install github.com/fiatjaf/nak@latest
#go install github.com/mdzz-club/nkcli@latest
## go install github.com/slok/grafterm@latest
#
#omz update


#flatpak remote-add --if-not-exists futr-stable https://flatpak.futrnostr.com/futr-stable.flatpakrepo
#flatpak install com.futrnostr.futr

##flatpak remote-add --if-not-exists futr-continuous https://flatpak.futrnostr.com/futr-continuous.flatpakrepo
##flatpak install com.futrnostr.futr

#cargo install --locked --force --git https://github.com/lumehq/coop --tag 0.1.4-alpha
#cargo install --locked --force --git https://github.com/lumehq/coop --branch master

#~/.cargo/bin/cargo install --locked --force --tag v10.5.2 --git https://github.com/erebe/wstunnel
##~/.cargo/bin/cargo install --locked --force --git https://github.com/0typos/wstunnel --branch fix/socks5
#sudo setcap CAP_NET_ADMIN=+eip ~/.cargo/bin/wstunnel
#
#~/.cargo/bin/cargo install --locked --force --tag v4.2.2 --git https://github.com/NOBLES5E/cproxy
#sudo chown root:root ~/.cargo/bin/cproxy
#sudo mv ~/.cargo/bin/cproxy /usr/local/sbin/
#
##~/.cargo/bin/cargo install --locked quicssh-rs
#~/.cargo/bin/cargo install --locked quicssh-rs-robust
#
#
#~/.cargo/bin/cargo install --locked wild-linker

#cargo install --locked --force --git https://github.com/damus-io/notedeck --tag v0.3.0

#cargo install --locked hexhog
#cargo install --locked cargo-unused-features
#cargo install --locked --rev 649aeac08b27a025bc9cdfb45255f4f4170d55e1 https://github.com/vsl-iil/cargo-unused-features

#RUSTFLAGS="-C target-cpu=native --cfg tokio_unstable" CFLAGS="${CFLAGS} -DCMAKE_POLICY_VERSION_MINIMUM=3.5" CXXFLAGS="${CXXFLAGS} -DCMAKE_POLICY_VERSION_MINIMUM=3.5" cargo install --locked --force --features=lang-cjk,video-ffmpeg --git https://github.com/mikedilger/gossip --tag v0.14.0
#RUSTFLAGS="-C target-cpu=native --cfg tokio_unstable" cargo install --locked --force --git https://github.com/mikedilger/gossip --tag v0.14.0



#sudo setcap 'CAP_NET_RAW,CAP_NET_ADMIN+ep' `which sslocal`
