#!/usr/bin/env ruby

args = ARGV.map do |i|
  case i
  when /(^[^-].*?):([0-9]*?):([0-9]*?):*$/
    filename = Regexp.last_match(1)
    line = Regexp.last_match(2)
    column = Regexp.last_match(3)
    column = (column.empty?) ? "1" : column
    File.exist?(filename) ? "#{filename} '+call cursor(#{line}, #{column})'" : i
  when /(^[^-].*?):([0-9]*$)/
    filename = Regexp.last_match(1)
    line = Regexp.last_match(2)
    File.exist?(filename) ? "#{filename} +#{line}" : i
  else
    i
  end
end.join(' ')

system("/usr/bin/nvim -p #{args}")
