#!/bin/bash

project_dir=$(cargo metadata --quiet --format-version=1 2>>/dev/null | jq --raw-output '.workspace_root')
project_dir_escaped=$(echo "${project_dir}" | sed 's!/!%!g')
export CARGO_TARGET_DIR="${HOME}/tmp/${project_dir_escaped}/target.rust-analyzer"

nvim_listen_address="/tmp/nvim-${USER}-${project_dir_escaped}"

/usr/bin/nvim --listen "${nvim_listen_address}" -p "$@"
