#!/bin/sh

current_dir="${PWD}"
if [ $(tmux list-panes | wc -l) -gt 1 ]; then
    tmux new-window "cd ${current_dir} ; source ~/scripts/tmux-cd-to-current-dir.sh ; ${SHELL}"
fi

tmux split-window -h -l 180 "source ~/scripts/tmux-cd-to-current-dir.sh ; vi $@ ; ${SHELL}"
tmux split-window -v -l 12 "source ~/scripts/tmux-cd-to-current-dir.sh ; ${SHELL}"
tmux select-pane -U
