#!/bin/bash

logger $1
logger $@

#if (echo "$1" | grep -q '^xmpp:'); then
#    gajim-remote add_contact $(echo "$1" | sed -e 's/^xmpp://')
if (echo "$1" | grep -q '\.pdf$'); then
    zathura "$1"
elif (echo "$1" | egrep -q '\.(txt|log)$'); then
    leafpad "$1"
else
    source /usr/bin/xdg-open
fi
