#!/bin/bash

#CHOICE=$(printf "quit\nhibernate\nreboot\nhalt\n"|~/.dwm/dmenu -p 'quit??!!')
~/.bin/$(echo -e 'standby\nreboot\nhalt\n'|~/.bin/dmenu -p 'quit??!!')
#~/.bin/$(echo -e 'hibernate\nreboot\nhalt\n'|~/.bin/dmenu -p 'quit??!!')

#case $CHOICE in
#	#quit)
#	#	sudo chvt 2
#	#	echo '0 quit' | awesome-client
#	#	#killall X;;
#	#	;;
#	reboot)
#		sudo chvt 1
#		#sudo reboot>>/dev/tty1;;
#		/usr/local/bin/reboot;;
#	halt)
#		sudo chvt 1
#		#sudo halt>>/dev/tty1;;
#		/usr/local/bin/halt;;
#	hibernate)
#		#echo 'status offline' >> ~/.mcabber/mcabber.fifo
#		lock -bg image:center,file=/home/sbar/pix/locked.png -cursor theme:name=mini -auth passwd &
#		#sudo hibernate --force>>/var/log/mydm.log;;
#		sudo /usr/local/sbin/hibernate.sh >> /var/log/mydm.log;;
#esac
