-vU
-vvv

#--format "bestvideo[height<=1080]+bestaudio"
--format "bestvideo[height<=1080][protocol!*=dash]+bestaudio"

--format "(bestvideo+bestaudio/bestvideo)[height<=1080][protocol!*=dash]/bestvideo[height<=1080]+bestaudio/best"

#--format "bestvideo[height<=1080][ext=mp4]+bestaudio"
--format-sort "res,codec:h264,codec:av1,codec:vp9"
--sub-format "ass/srt/best"

--concurrent-fragments 32
#--limit-rate 1M

#--paths "temp:/var/tmp/000"
--no-write-comments
--no-post-overwrites
#--keep-fragments
